version: "3.7"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - 9091:9091
    volumes:
      - ./secret.key:/secret/key.txt
  vault:
    build:
      context: .
      dockerfile: Dockerfile.vault
