apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-service-deployment
  labels:
    service-name: echo
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      service-name: echo
  template:
    metadata:
      labels:
        service-name: echo
        version: v3.0.0
    spec:
      containers:
        - name: echo-server
          image: k8s.gcr.io/liveness
          args:
            - /server
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
              httpHeaders:
              - name: Custom-Header
                value: Awesome
            initialDelaySeconds: 3
            periodSeconds: 3