global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'app-monitor'

# extra: include rules for alerting
#rule_files:
#  - rules.yml

# IMPORTANT BIT HERE: targets for scraping mtrics from
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'prom:9090' ]

  - job_name: 'telegraf'
    scrape_interval: 5s
    static_configs:
      - targets: ['telegraf:9100']

  - job_name: 'app-server'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'app:2112' ]